"""
Meeting article generator for Jekyll sites.

Generates Jekyll-formatted meeting articles from analyzed topic data.
Creates LLM prompts for article generation and prepares Jekyll front matter.

The pipeline:
1. Reads topic analysis JSON (from analyzer)
2. Builds metadata (meeting info, duration)
3. Generates structured LLM prompt
4. Outputs Jekyll draft template for manual completion
"""

import argparse
import json
import sys
import unicodedata
from pathlib import Path
from datetime import datetime

import yaml


# =========================
# CONFIG
# =========================

# Default layout for Jekyll
DEFAULT_LAYOUT = "meeting"

# Default output files
DEFAULT_PROMPT_FILE = "llm_prompt.txt"
DEFAULT_JEKYLL_DRAFT = "jekyll_draft.md"


# =========================
# HELPERS
# =========================

def _normalize_text(text):
    """
    Normalize Unicode text by removing diacritics.

    Args:
        text: Text to normalize (str)

    Returns:
        str: Normalized lowercase text without diacritics
    """
    text = unicodedata.normalize("NFKD", text)
    text = "".join(c for c in text if not unicodedata.combining(c))
    return text.lower()


# =========================
# METADATA GENERATION
# =========================

def build_meeting_metadata(topics, meeting_date, meeting_number, layout=DEFAULT_LAYOUT):
    """
    Build Jekyll front matter metadata from topics.

    Metadata is NEVER generated by LLM - it's deterministic from input data.

    Args:
        topics: List of topic dicts from analyzer
        meeting_date: Meeting date in YYYY-MM-DD format (str)
        meeting_number: Meeting sequence number (int)
        layout: Jekyll layout name (str)

    Returns:
        dict: Jekyll front matter fields:
            - layout: Jekyll layout name
            - title: Page title
            - meeting_date: Date in YYYY-MM-DD
            - meeting_number: Meeting sequence number
            - meeting_duration: Human readable duration (e.g., "2 h 15 min")
            - meeting_duration_minutes: Total duration in minutes
    """
    # Calculate total duration from topics
    total_minutes = int(sum(t.get("time_minutes", 0) for t in topics))
    hours = total_minutes // 60
    minutes = total_minutes % 60

    return {
        "layout": layout,
        "title": f"Jednání zastupitelstva – {meeting_date}",
        "meeting_date": meeting_date,
        "meeting_number": meeting_number,
        "meeting_duration": f"{hours} h {minutes} min",
        "meeting_duration_minutes": total_minutes,
    }


# =========================
# TOPIC PREPARATION
# =========================

def _derive_meeting_character(topics):
    """Derive a simple meeting character label for legacy topic lists."""
    if not topics:
        return "mixed_focus"

    ordered = sorted(topics, key=lambda topic: -topic.get("time_minutes", 0))
    total_minutes = sum(topic.get("time_minutes", 0) for topic in ordered)
    dominant_share = (
        ordered[0].get("time_minutes", 0) / total_minutes
        if total_minutes else 0.0
    )

    if dominant_share >= 0.45:
        return "dominated_by_one_topic"
    if len(ordered) >= 6 and dominant_share <= 0.25:
        return "spread_across_many_topics"
    return "mixed_focus"


def prepare_topics_for_llm(topics_or_brief):
    """
    Normalize analyzer output into a prompt-ready article brief.

    Supports both the new article-brief structure and the older plain topic list
    for backwards compatibility.

    Args:
        topics_or_brief: List of topic dicts or article brief dict from analyzer

    Returns:
        dict: Article brief with meeting_overview, priority_topics, and topics
    """
    if isinstance(topics_or_brief, dict):
        topics = sorted(topics_or_brief.get("topics", []), key=lambda topic: topic.get("order", 0))
        return {
            "meeting_overview": topics_or_brief.get("meeting_overview", {}),
            "priority_topics": topics_or_brief.get("priority_topics", []),
            "topics": topics,
        }

    topics = sorted(topics_or_brief, key=lambda topic: topic.get("order", 0))
    total_minutes = round(sum(topic.get("time_minutes", 0) for topic in topics), 1)
    longest_topics = sorted(
        topics,
        key=lambda topic: (-topic.get("time_minutes", 0), topic.get("order", 0))
    )[:3]

    for topic in topics:
        evidence_items = []
        for item in topic.get("evidence", []):
            if isinstance(item, dict):
                evidence_items.append(item)
            else:
                evidence_items.append({
                    "text": item,
                    "evidence_type": "discussion",
                })
        topic["evidence"] = evidence_items

    return {
        "meeting_overview": {
            "total_meeting_minutes": total_minutes,
            "included_topic_count": len(topics),
            "top_3_longest_topics": [
                {
                    "order": topic.get("order"),
                    "topic_hint": topic.get("topic_hint"),
                    "time_minutes": round(topic.get("time_minutes", 0), 1),
                    "time_range": topic.get("time_range"),
                    "discussion_intensity": topic.get("discussion_intensity"),
                }
                for topic in longest_topics
            ],
            "procedural_share": round(
                sum(topic.get("time_minutes", 0) for topic in topics if topic.get("topic_type") == "procedural") / total_minutes,
                2
            ) if total_minutes else 0.0,
            "discussion_share": round(
                sum(topic.get("time_minutes", 0) for topic in topics if topic.get("topic_type") == "discussion") / total_minutes,
                2
            ) if total_minutes else 0.0,
            "meeting_character": _derive_meeting_character(topics),
            "dominant_topic_share": round(
                longest_topics[0].get("time_minutes", 0) / total_minutes,
                2
            ) if total_minutes and longest_topics else 0.0,
        },
        "priority_topics": [
            {
                "order": topic.get("order"),
                "topic_hint": topic.get("topic_hint"),
                "time_minutes": round(topic.get("time_minutes", 0), 1),
                "time_range": topic.get("time_range"),
                "topic_type": topic.get("topic_type"),
                "discussion_intensity": topic.get("discussion_intensity"),
                "topic_summary_hint": topic.get("topic_summary_hint"),
            }
            for topic in longest_topics
        ],
        "topics": topics,
    }


# =========================
# LLM PROMPT GENERATION
# =========================

def build_llm_prompt(article_brief):
    """
    Build structured prompt for LLM article generation.

    Args:
        article_brief: Prepared article brief from prepare_topics_for_llm()

    Returns:
        str: Complete LLM prompt with instructions and data
    """
    meeting_overview = article_brief.get("meeting_overview", {})
    priority_topics = article_brief.get("priority_topics", [])
    topics = article_brief.get("topics", [])

    return f"""
Jsi redaktor regionálního zpravodajství.
Píšeš čtivý, faktický článek o průběhu jednání zastupitelstva v podobě lokálního zpravodajství.

Writing Objective:
- napiš středně dlouhý článek bez mezititulků, který čtenáři rychle vysvětlí, co na jednání zabralo nejvíc času a proč to bylo důležité
- článek má být informačně hutný, konkrétní a dobře plynoucí, ne mechanický přepis bod po bodu
- otevři text nejdůležitějšími nebo časově dominantními tématy z priority listu, potom plynule pokryj zbytek jednání v chronologii

Reader Value:
- ukaž konkrétní rozhodnutí, spory, praktické dopady na obyvatele, místa, částky, termíny a opakující se obavy, pokud jsou v podkladech
- zohledni, kolik času bylo kterému tématu věnováno; dlouhá témata rozveď, rutinní procedurální body stlač do krátké zmínky
- propojuj související témata a obměňuj rytmus vět, aby text nepůsobil jako jedna odstavecová šablona pro každý JSON bod

Pravidla:
- nevymýšlej žádná fakta, jména, citace, čísla ani závěry, které nejsou v podkladech
- nepiš hodnotící nebo komentátorský text; silnější vysvětlující formulace používej jen tehdy, když jsou opřené o evidence
- vyhni se prázdným větám typu "zastupitelé dále řešili různé body", pokud mají podklady konkrétní obsah
- když jsou podklady řídké nebo šumové, přiznej stručnost tématu místo doplňování falešné konkrétnosti
- piš česky

Cílová délka:
- summary: 3 až 4 věty, faktický abstrakt hlavních témat a těžiště jednání
- article_body: středně dlouhý souvislý text; u několikahodinového jednání míř zhruba na 700 až 1100 slov, ale rutinní body komprimuj a při chudých podkladech raději zkrať

Výstup vrať přesně v tomto tvaru:
SUMMARY:
3-4 věty

ARTICLE_BODY:
souvislý text článku bez nadpisů

Přehled jednání:
{json.dumps(meeting_overview, ensure_ascii=False, indent=2)}

Priority Topics:
{json.dumps(priority_topics, ensure_ascii=False, indent=2)}

Topics In Reading Order:
{json.dumps(topics, ensure_ascii=False, indent=2)}
""".strip()


# =========================
# JEKYLL OUTPUT
# =========================

def build_jekyll_draft(metadata, summary_placeholder="<<< VLOŽ SHRNUTÍ (3-4 VĚTY) >>>", article_placeholder="<<< VLOŽ TEXT ČLÁNKU ZDE >>>"):
    """
    Build Jekyll page draft with metadata and placeholders.

    Creates a valid Jekyll front matter page ready for manual completion.

    Args:
        metadata: Metadata dict from build_meeting_metadata()
        summary_placeholder: Placeholder text for summary (str)
        article_placeholder: Placeholder text for article body (str)

    Returns:
        str: Complete Jekyll page with YAML front matter and placeholders
    """
    header = dict(metadata)
    header["summary"] = summary_placeholder

    # Generate YAML front matter
    yaml_text = yaml.safe_dump(
        header,
        allow_unicode=True,
        sort_keys=False,
        width=80
    )

    # Combine front matter and body
    content = (
        f"---\n{yaml_text}---\n\n"
        f"{article_placeholder}\n"
    )

    return content


# =========================
# MAIN PIPELINE
# =========================

def generate_article(
    topics_file,
    meeting_date,
    meeting_number,
    output_dir=None,
    layout=DEFAULT_LAYOUT,
    prompt_file=None,
    jekyll_file=None
):
    """
    Generate meeting article prompt and Jekyll template.

    Process:
    1. Load topics from analyzer output
    2. Build deterministic metadata
    3. Prepare topics for LLM
    4. Generate LLM prompt
    5. Create Jekyll draft template

    Args:
        topics_file: Path to topics JSON from analyzer (Path or str)
        meeting_date: Meeting date in YYYY-MM-DD format (str)
        meeting_number: Meeting sequence number (int)
        output_dir: Output directory for generated files (Path or str, optional)
        layout: Jekyll layout name (str)
        prompt_file: Custom LLM prompt filename (str, optional)
        jekyll_file: Custom Jekyll draft filename (str, optional)

    Returns:
        dict: Paths to generated files:
            - prompt_path: Path to LLM prompt file
            - jekyll_path: Path to Jekyll draft file

    Raises:
        FileNotFoundError: If topics file doesn't exist
        ValueError: If date format is invalid or data is malformed
    """
    topics_file = Path(topics_file)

    # Validate inputs
    if not topics_file.exists():
        raise FileNotFoundError(f"Topics file not found: {topics_file}")

    # Validate date format
    try:
        datetime.strptime(meeting_date, "%Y-%m-%d")
    except ValueError:
        raise ValueError(f"Invalid date format: {meeting_date}. Use YYYY-MM-DD format.")

    # Setup output directory
    if output_dir:
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
    else:
        output_dir = topics_file.parent

    # Setup output filenames
    prompt_path = output_dir / (prompt_file or DEFAULT_PROMPT_FILE)
    jekyll_path = output_dir / (jekyll_file or DEFAULT_JEKYLL_DRAFT)

    # Load topics
    print(f"▶ Loading topics from {topics_file}...")
    try:
        topics = json.loads(topics_file.read_text(encoding="utf-8"))
        if not isinstance(topics, (list, dict)):
            raise ValueError("Topics file must contain a JSON array or article brief object")
    except json.JSONDecodeError as e:
        raise ValueError(f"Invalid JSON in topics file: {e}") from e

    # Build metadata (deterministic, not from LLM)
    print("▶ Building metadata...")
    prepared_topics = prepare_topics_for_llm(topics)
    metadata = build_meeting_metadata(prepared_topics["topics"], meeting_date, meeting_number, layout)

    # Prepare article brief for LLM
    print("▶ Preparing article brief for LLM...")

    # Generate LLM prompt
    print("▶ Generating LLM prompt...")
    llm_prompt = build_llm_prompt(prepared_topics)
    prompt_path.write_text(llm_prompt, encoding="utf-8")

    # Generate Jekyll draft
    print("▶ Generating Jekyll draft...")
    jekyll_content = build_jekyll_draft(metadata)
    jekyll_path.write_text(jekyll_content, encoding="utf-8")

    # Print summary
    print("\n✅ Article generation complete!")
    print(f"\n📝 LLM Prompt: {prompt_path}")
    print(f"📄 Jekyll Draft: {jekyll_path}")

    print("\n📋 Metadata:")
    print(json.dumps(metadata, indent=2, ensure_ascii=False))

    print("\n⚡ Next steps:")
    print("  1. Send LLM prompt to your preferred LLM")
    print("  2. Copy SUMMARY into front matter and ARTICLE_BODY into Jekyll draft")
    print("  3. Review and publish")

    return {
        "prompt_path": str(prompt_path),
        "jekyll_path": str(jekyll_path),
        "metadata": metadata
    }


def main():
    """
    Main entry point for article generator.

    Generates LLM prompts and Jekyll drafts from analyzed meeting topics.

    Command line arguments:
        --topics, -i: Path to topics JSON file from analyzer (required)
        --date, -d: Meeting date in YYYY-MM-DD format (required)
        --number, -n: Meeting sequence number (required)
        --outdir, -o: Output directory (default: same as topics file)
        --layout: Jekyll layout name (default: meeting)
        --prompt-file: Custom LLM prompt filename
        --jekyll-file: Custom Jekyll draft filename

    Outputs:
        - llm_prompt.txt: Structured prompt for LLM
        - jekyll_draft.md: Jekyll page template with placeholders
    """
    parser = argparse.ArgumentParser(
        description="Generate meeting article from analyzed topics",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Basic usage
  python generate_meeting_article.py \\
    --topics output/llm_input.json \\
    --date 2025-01-15 \\
    --number 23

  # Custom output directory
  python generate_meeting_article.py \\
    -i output/llm_input.json \\
    -d 2025-01-15 \\
    -n 23 \\
    -o articles/

  # Custom Jekyll layout
  python generate_meeting_article.py \\
    -i output/llm_input.json \\
    -d 2025-01-15 \\
    -n 23 \\
    --layout custom-meeting

Workflow:
  1. Run analyzer: analyze_meeting_topics.py --file transcript.txt
  2. Run this tool: generate_meeting_article.py --topics llm_input.json --date YYYY-MM-DD --number N
  3. Send llm_prompt.txt to LLM (Claude, GPT, etc.)
  4. Copy LLM output into jekyll_draft.md
  5. Review and publish
        """
    )

    parser.add_argument(
        "--topics", "-i",
        type=Path,
        required=True,
        help="Input topics JSON file (from analyzer)"
    )

    parser.add_argument(
        "--date", "-d",
        type=str,
        required=True,
        help="Meeting date in YYYY-MM-DD format"
    )

    parser.add_argument(
        "--number", "-n",
        type=int,
        required=True,
        help="Meeting sequence number"
    )

    parser.add_argument(
        "--outdir", "-o",
        type=Path,
        help="Output directory (default: same as topics file)"
    )

    parser.add_argument(
        "--layout",
        type=str,
        default=DEFAULT_LAYOUT,
        help=f"Jekyll layout name (default: {DEFAULT_LAYOUT})"
    )

    parser.add_argument(
        "--prompt-file",
        type=str,
        help=f"Custom LLM prompt filename (default: {DEFAULT_PROMPT_FILE})"
    )

    parser.add_argument(
        "--jekyll-file",
        type=str,
        help=f"Custom Jekyll draft filename (default: {DEFAULT_JEKYLL_DRAFT})"
    )

    args = parser.parse_args()

    # Run article generation
    try:
        generate_article(
            topics_file=args.topics,
            meeting_date=args.date,
            meeting_number=args.number,
            output_dir=args.outdir,
            layout=args.layout,
            prompt_file=args.prompt_file,
            jekyll_file=args.jekyll_file
        )
    except Exception as e:
        print(f"❌ Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
